import type { DriverZone, GraphNode, TransportMode } from "@/types";

/** Map a graph node to a DriverZone-shaped object for `ZoneMapTooltip`. */
export function graphNodeToDriverZone(node: GraphNode): DriverZone {
  return {
    id: node.zone_id,
    owner_user_id: node.transport_id,
    driver_name: node.transport_name,
    zone_name: node.zone_name,
    resolution: node.resolution,
    h3_cells: node.cells,
    cell_count: node.h3_cell_count,
    transport_mode: (node.transport_method ?? "land") as TransportMode,
    boundary: null,
    departure_hub: node.departure_hub,
    arrival_hub: node.arrival_hub,
    departure_time: node.departure_time,
    arrival_time: node.arrival_time,
    operation_date: null,
    operation_start_date: null,
    operation_end_date: null,
    schedule_pattern: "daily",
    weekday_start: null,
    weekday_end: null,
    month_day_start: null,
    month_day_end: null,
    operating_start_time: null,
    operating_end_time: null,
    base_fee: null,
    cost_per_km: null,
    cost_per_hour: null,
    cost_per_h3_cell: null,
    cost_per_kg: null,
    cost_per_volume_unit: null,
    time_of_day_factor: null,
    minimum_fee: null,
    currency: "USD",
    pricing_mode: "system",
    pricing_region_id: null,
    available: !node.is_isolated,
    trust_payment_forwarder: false,
    driver_trustworthiness: 0,
    created_at: "",
    updated_at: "",
  };
}
